### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by jrlivesey**
@gitK2, would appreciate any feedback on this that you can provide—especially on Problems 3 & 4.

### CODE REVIEW

**Comment by gitK2** [comment]
Hi @jrlivesey , sorry I didn't get to comment on your lab 2 until now, and thanks for your patience. I have a few suggestions for your lab report:
On problem 1, I think you seemed to imply that summing the Poisson distribution keeps it a Poisson distribution, but does not make it closer to a normal distribution. However the central limit theorem states that summing a distribution many times also makes it approach a normal distribution. I agree with what you wrote about taking the average though.
On problem 2, some of the lines get wonky at the bottom of the semi-log plot, but I don't know if that's easy or necessary to fix.
On problem 3, the instructions state that "... the background appears as a zero-mean Gaussian with constant width over the image." You specified that mu = 7.5, which I think means you set the mean to 7.5 instead of 0. Also, I think you can explain more thoroughly how you scaled up the background noise by 10,000x. It seems that you divided your signal by 10,000 but I'm not sure whether or not that has the same effect.
Overall, I still think you did a great job on your lab, and reading it I think I figured out several things I wasn't sure about before.

**Comment by jrlivesey** [comment]
Thank you for your comments, @gitK2! I've incorporated your suggestions for Problems 2 & 3. On the matter of the Central Limit Theorem, I believe it's only the case that an arbitrary distribution tends toward the normal distribution after being summed and _normalized_, i.e. averaged. Thanks again!

**Comment by jrlivesey** [comment]
I'm submitting this for your approval, @hrzhao76.

**Comment by gitK2** [comment]
@jrlivesey Oops you're right, the central limit theorem might not apply to sums that aren't averaged.  
I also looked at problem 4 again and I think problem 4D asks what happens when you change the trials factor (10,000) by orders of magnitude, not whether the signal necessary to reach 5 sigma changes by orders of magnitude.  
Lastly in problem 3 I saw you changed the mean to 0 in your code, but it still has the old mu in your markdown text.

**Comment by jrlivesey** [comment]
Thank you @gitK2! Someday I'll learn how to read instructions.

**Pull request merged**
